# Generated by Django 4.2.3 on 2023-07-03 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("data_entry", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customentrychangelog",
            name="entry_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entry_logs",
                to="data_entry.customentry",
            ),
        ),
        migrations.AlterField(
            model_name="evententrychangelog",
            name="entry_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entry_logs",
                to="data_entry.evententry",
            ),
        ),
        migrations.AlterField(
            model_name="healthinstitutionentrychangelog",
            name="entry_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entry_logs",
                to="data_entry.healthinstitutionentry",
            ),
        ),
        migrations.AlterField(
            model_name="professionentrychangelog",
            name="entry_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entry_logs",
                to="data_entry.professionentry",
            ),
        ),
    ]
