# Generated by Django 4.2.3 on 2023-07-03 23:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data_entry", "0002_alter_customentrychangelog_entry_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="evententrychangelog",
            name="entry_id",
        ),
        migrations.RemoveField(
            model_name="evententrychangelog",
            name="event_triggered_by",
        ),
        migrations.RemoveField(
            model_name="healthinstitutionentrychangelog",
            name="entry_id",
        ),
        migrations.RemoveField(
            model_name="healthinstitutionentrychangelog",
            name="event_triggered_by",
        ),
        migrations.RemoveField(
            model_name="professionentrychangelog",
            name="entry_id",
        ),
        migrations.RemoveField(
            model_name="professionentrychangelog",
            name="event_triggered_by",
        ),
        migrations.DeleteModel(
            name="CustomEntryChangeLog",
        ),
        migrations.DeleteModel(
            name="EventEntryChangeLog",
        ),
        migrations.DeleteModel(
            name="HealthInstitutionEntryChangeLog",
        ),
        migrations.DeleteModel(
            name="ProfessionEntryChangeLog",
        ),
    ]
