version: 2
steps:
  - checkout
  - run:
      name: Install Packages
      command: |
        python3 -m venv env
        . env/bin/activate
        pip install -r requirements.txt

  - run:
      name: Test with TestCase
      command: |
        . env/bin/activate
        python manage.py test